#! /usr/bin/env python
import sys

from lib import board, moves

brd = board.from_file(sys.argv[1])
moves = moves.list_from_file(sys.argv[2])

num_moves = brd.execute_moves(moves)

if brd.is_solved():
    print "Solved in " + str(num_moves) + " move(s)."
else:
    print "Not solved."