#! /usr/bin/env python
import sys
import random

from lib.board import Board

size = int(sys.argv[1])
num_moves = int(sys.argv[2])

base_rows = []
for row in range(size):
    base_rows.append([])
    for col in range(size):
        base_rows[row].append((row * size) + col + 1)

base_rows[size - 1][size - 1] = "*"

board = Board(base_rows)

for _ in range(num_moves):
    board.move(random.choice(board.valid_moves()))

board.write_to_file(sys.argv[3])